//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaTBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeteriaEntities : DbContext
    {
        public CafeteriaEntities()
            : base("name=CafeteriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<Asentamiento> Asentamiento { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<CorteVenta> CorteVenta { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<DescuentoVenta> DescuentoVenta { get; set; }
        public virtual DbSet<DevolucionCompra> DevolucionCompra { get; set; }
        public virtual DbSet<DevolucionVenta> DevolucionVenta { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Platillo> Platillo { get; set; }
        public virtual DbSet<PlatilloMaterial> PlatilloMaterial { get; set; }
        public virtual DbSet<PlatilloVenta> PlatilloVenta { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<TipoAsentamiento> TipoAsentamiento { get; set; }
        public virtual DbSet<TipoCliente> TipoCliente { get; set; }
        public virtual DbSet<TipoPlatillo> TipoPlatillo { get; set; }
        public virtual DbSet<TipoProveedor> TipoProveedor { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
    }
}
